### PR TITLE
API

### PR DESCRIPTION
**Pull request by hildjj**
Modernize the API.  Switch to ES6, promises, and do a general cleanup pass.

### CODE REVIEW

**Comment by hildjj** [comment]
@ekr, I'm waiting on #20 at least before I land this, since it's likely to cause a merge that I'm willing to handle.  Let me know when you're ready.

**Comment by hildjj** [comment]
@ekr, ok to send new patches.  Please pull from main first, then `npm install` again to ensure you've got the latest dependencies.

**Comment by ekr** [comment]
I see that grammar.js is using the new export styles. Do I need a new flag for peggy?

**Comment by hildjj** [comment]
Yes.  Use `npm run prepare` and it will do the right thing.  I'll likely be changing that to `npm run build` in the change that adds web support, to keep everything parallel.  You can see the current list of scripts with `npm run` and no script name.

**Comment by ekr** [comment]
Thanks!

**Comment by hildjj** [comment]
It looks like there might be a spurious `genversion` in one version of package.json, which you can delete if it's in yours.  I'll make sure it's fixed in my next big patch.

**Comment by hildjj** [comment]
@ekr I just cleaned this up in a quick patch in #26

**Pull request merged**
