### PR TITLE
Allow setting options on the command line

### PR DESCRIPTION
**Pull request by ekr**

### CODE REVIEW

**Comment by ekr** [comment]
Should have run more tests.

**Comment by hildjj** [comment]
I'll add CLI tests when fixing #29

**Comment by ekr** [comment]
Was just going to ask about that. Thanks!

**Comment by ekr** [comment]
Give me a minute and I'll update README.md.

**Comment by ekr** [comment]
Hmm.... And also missed the case with no value. Will fix that too.

**Comment by ekr** [comment]
Aargh. I really needed to do more testing. Sit tight.

**Comment by ekr** [comment]
OK I think this works correctly, with the exception that the command line overrides the in-file settings rather than the other way around. Thoughts on the best way to fix that? It seems like we need a global properties object that then gets overridden by the command line?

**Comment by hildjj** [comment]
What if the command line overriding the file is just intentional?  It's a legitimate choice.

**Comment by hildjj** [comment]
Also please test multiple input files on the command line.

**Comment by ekr** [comment]
> What if the command line overriding the file is just intentional? It's a legitimate choice.

My general take was that the specific overrides the general, but obviously I'm happy not to change it.


> Also please test multiple input files on the command line.

I just did and it looked OK, but maybe I'm missing a bug?

It looks like you haven't added CLI tests yet, but if you want to add them first, I'm happy to write some for this PR.

**Comment by hildjj** [comment]
I want to land this, then #27, then I'll do the basics of the CLI tests, and then you can add some more, if that's ok?

**Comment by ekr** [comment]
SGTM

**Comment by hildjj** [comment]
OK, #27 landed on top of this.  Look at https://hildjj.github.io/quence/ and file issues, feature requests, UI improvement requests, please.  I'll deal with CLI testing tomorrow.

**Pull request merged**
