### PR TITLE
Fix the self "lost packet" case.

### PR DESCRIPTION
**Pull request by ekr**
Add tests.

@hildjj this seems to generate the right output but I'm not quite sure what to look for in the snaps. Should I be looking at the SVG file? Something else?

### CODE REVIEW

**Comment by hildjj** [comment]
If the SVG file looks right, and there's nothing obviously wrong with the snaps, you're file.  "obviously wrong" would be things changing that shouldn't have (which you'd mostly see in the rendered SVG), but I like to take a pass through and make sure I understand the gist of the changes.  In this case, the width changed, and that threw off a bunch of coordinates from previous arrows in addition to the things you added, so it's fine.

**Comment by hildjj** [comment]
I also like to run `make` in the examples directory, and look at what's generated.  In this case, there's still an issue with the X and the line end not matching:

Screenshot 2023-01-09 at 9 29 23 AM

**Comment by ekr** [comment]
Aargg... Thanks. I see what's going on here. Thanks!

**Comment by ekr** [comment]
OK how's this?

**Comment by hildjj** [comment]
Needs lint fixes, otherwise LGTM.  I'll add lint to the CI.  `npm run lint` will show the issues.

**Comment by ekr** [comment]
Thanks. Do you have a preferred lint setup so I can run it locally?

**Comment by hildjj** [comment]
If you do `npm install` to ensure everything is up-to-date, then `npm run lint` you should see them locally.  Here's what I get:

```
quence/lib/driver.js
  219:17  error  Extra semicolon                                                  semi
  219:17  error  Expected this semicolon to be at the beginning of the next line  semi-style
  219:18  error  Trailing spaces not allowed                                      no-trailing-spaces
  223:20  error  Extra semicolon                                                  semi
  223:20  error  Expected this semicolon to be at the beginning of the next line  semi-style
  228:24  error  Operator '===' must be spaced                                    space-infix-ops
  229:33  error  Operator '/' must be spaced                                      space-infix-ops
  229:39  error  Extra semicolon                                                  semi
  229:39  error  Expected this semicolon to be at the beginning of the next line  semi-style
  230:19  error  Extra semicolon                                                  semi
  231:6   error  Trailing spaces not allowed                                      no-trailing-spaces
  242:45  error  Missing trailing comma                                           comma-dangle
```

**Comment by hildjj** [comment]
LGTM, thanks.

**Comment by hildjj** [comment]
Please let me land the API branch before doing more.

**Comment by ekr** [comment]
SG. Please tag me when you land that branch.

**Comment by hildjj** [comment]
In case you didn't see it on #24, it's done now.  Please pull main and work from there after doing `npm install` to pick up latest dependencies.

**Pull request merged**
