### PR TITLE
Render a lost packet

### PR DESCRIPTION
**Pull request by ekr**
This PR allows you to have a lost packet by using "#" as the arrowhead. The result is a line that only goes halfway across and ends in an X.

### CODE REVIEW

**Comment by ekr** [comment]
Oops. This doesn't put the label in the right place on R->L. Need to fix.

**Comment by ekr** [comment]
Label is fixed.

**Comment by hildjj** [comment]
I'll update all the deps, get the tests to pass, and add an example before doing a release.

**Comment by ekr** [comment]
You may want to wait... I've got some more enhancements in the pipe. Specifically

1. Improve handling of messages that take multiple time slices. Right now if you do

```
Sender -> Receiver: Packet (1) [duration=3]
Sender -> Receiver: Packet (2) [duration=3]
```

quence starts the send of packet after the receipt of packet 1 rather than in parallel.
I'd be interested in suggested notation here, as making `advance` allow negative is kind of gross.

2. Add time labels on the sides.
3. Add notes like wsd does. 

LMK if you'd like me to file issues on these or just PRs as they are ready.

**Comment by hildjj** [comment]
My updates are ready to go in #17.  I think it would be easiest if you rebase your follow-ups onto that, if that's ok?

**Comment by ekr** [comment]
No problem. I'm still hacking away on these, so it'll probably be next week at the earliest, and I can easily rebase.

**Comment by hildjj** [comment]
Nod.  Merging now.  Please note the updated deps, which has a few lint tweaks.  Also, please add new syntaxes to examples/test.wsd, update the corresponding test snapshots with `npm run snaps`, and make sure the diff makes sense with your change.  With all of that, the CI tests should all be green now.

**Comment by ekr** [comment]
Willdo. Thanks for the clear instructions on what to do.

**Comment by hildjj** [comment]
Regarding syntax, should the left and right timelines progress independently?  Also, I don't mind -advance that much if that's the only way.  I can imagine a case where you want to send two messages from the same time, for instance.

**Pull request merged**
